version: '3'

services:
  cert-generator:
    build:
      context: .
      dockerfile: Dockerfile-cert-generator
    volumes:
      - ./certs:/certs
      - ./scripts/generate_cert.sh:/generate_cert.sh
    environment:
      SERVER_KEY_NAME: server.key
      SERVER_CERT_NAME: server.crt
    command: sh -c "./generate_cert.sh"

  backend:
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - '5443:5000'
    volumes:
      - ./certs:/app/certs
    environment:
      NODE_ENV: production
      PORT: 5000
      HOST: 0.0.0.0
      HTTPS: true
      SERVER_KEY_NAME: server.key
      SERVER_CERT_NAME: server.crt
    depends_on:
      - cert-generator
